# Generated by Django 5.2.8 on 2025-11-06 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=100)),
                ('rut_organizacion', models.CharField(max_length=13, unique=True)),
                ('plan_suscripcion', models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=10)),
                ('estado_suscripcion', models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo'), ('suspendido', 'Suspendido')], default='inactivo', max_length=10)),
                ('fecha_inicio_suscripcion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('fecha_inicio_proyecto', models.DateField()),
                ('fecha_fin_proyecto', models.DateField()),
                ('presupuesto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_proyecto', models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo'), ('completado', 'Completado'), ('en_pausa', 'En Pausa')], default='inactivo', max_length=20)),
                ('id_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizacion')),
            ],
        ),
    ]
