# Generated by Django 5.2.8 on 2025-11-11 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rol_usuario_rol_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('rut_proveedor', models.CharField(max_length=13, unique=True)),
                ('email_proveedor', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_registro', models.DateField()),
                ('nro_documento', models.CharField(max_length=50)),
                ('tipo_doc_transaccion', models.CharField(choices=[('factura electrónica', 'Factura Electrónica'), ('factura exenta', 'Factura Exenta'), ('boleta de compra', 'Boleta de Compra'), ('boleta de honorarios', 'Boleta de Honorarios')], default='factura electrónica', max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proveedor', 'nro_documento')},
            },
        ),
    ]
