# Generated by Django 5.2.8 on 2025-11-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proveedor_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='monto_ejecutado_proyecto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Item_Presupuestario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item_presupuesto', models.CharField(max_length=100)),
                ('monto_asignado_item', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_ejecutado_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Subitem_Presupuestario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subitem_presupuesto', models.CharField(max_length=100)),
                ('monto_asignado_subitem', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_ejecutado_subitem', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('item_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item_presupuestario')),
            ],
        ),
    ]
