# Generated by Django 5.2.8 on 2025-11-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proyecto_monto_ejecutado_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_evidencia', models.FileField(upload_to='evidencias/')),
                ('tipo_archivo', models.CharField(max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('nombre_evidencia', models.CharField(max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Log_transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_accion', models.DateTimeField(auto_now_add=True)),
                ('accion_realizada', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo')], default='creacion', max_length=15)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion_Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evidencia')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaccion')),
            ],
        ),
    ]
