# Generated by Django 5.2.8 on 2025-11-24 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_evidencia_log_transaccion_transaccion_evidencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencia',
            options={'ordering': ['-fecha_carga']},
        ),
        migrations.AlterModelOptions(
            name='item_presupuestario',
            options={'ordering': ['nombre_item_presupuesto']},
        ),
        migrations.AlterModelOptions(
            name='subitem_presupuestario',
            options={'ordering': ['nombre_subitem_presupuesto']},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha_registro', '-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='evidencia',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False, help_text='Eliminación lógica'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='evidencia_anterior',
            field=models.ForeignKey(blank=True, help_text='Referencia a la versión anterior si existe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_siguientes', to='api.evidencia'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='usuario_carga',
            field=models.ForeignKey(blank=True, help_text='Usuario que cargó la evidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_cargadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='usuario_eliminacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó la evidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_eliminadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='version',
            field=models.IntegerField(default=1, help_text='Número de versión del documento'),
        ),
        migrations.AddField(
            model_name='item_presupuestario',
            name='categoria_item',
            field=models.CharField(blank=True, help_text='Categoría del ítem para validar contra la categoría del gasto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='categoria_gasto',
            field=models.CharField(blank=True, help_text='Categoría del gasto para validar contra el ítem presupuestario', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado_transaccion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', help_text='Estado de la transacción en el flujo de aprobación', max_length=15),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='item_presupuestario',
            field=models.ForeignKey(blank=True, help_text='Ítem presupuestario asociado a esta transacción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.item_presupuestario'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='numero_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='numero_operacion_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='subitem_presupuestario',
            field=models.ForeignKey(blank=True, help_text='Subítem presupuestario asociado a esta transacción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.subitem_presupuestario'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='egreso', help_text='Indica si es un ingreso o egreso', max_length=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario_aprobador',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobó la transacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='tipo_archivo',
            field=models.CharField(help_text='Tipo MIME del archivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin proyecto', 'Admin Proyecto'), ('ejecutor', 'Ejecutor'), ('auditor', 'Auditor'), ('directivo', 'Directivo')], default='ejecutor', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_registro',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['proyecto', 'eliminado'], name='api_evidenc_proyect_5d023f_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['fecha_carga'], name='api_evidenc_fecha_c_b8b5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='item_presupuestario',
            index=models.Index(fields=['proyecto'], name='api_item_pr_proyect_b94b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='subitem_presupuestario',
            index=models.Index(fields=['item_presupuesto'], name='api_subitem_item_pr_4d06b5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['proyecto', 'estado_transaccion'], name='api_transac_proyect_6548f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha_registro', 'tipo_transaccion'], name='api_transac_fecha_r_283a18_idx'),
        ),
    ]
