# Generated by Django 5.2.8 on 2025-11-24 20:41

from django.db import migrations
from django.utils import timezone
from datetime import datetime


def fill_timestamps(apps, schema_editor):
    """
    Llena los campos fecha_creacion y fecha_actualizacion para transacciones existentes.
    Usa fecha_registro convertida a datetime, o timezone.now() si no hay fecha_registro.
    """
    Transaccion = apps.get_model('api', 'Transaccion')
    
    for transaccion in Transaccion.objects.filter(fecha_creacion__isnull=True):
        # Usar fecha_registro convertida a datetime, o timezone.now() como fallback
        if transaccion.fecha_registro:
            # Convertir date a datetime usando la hora actual
            fecha_creacion = timezone.make_aware(
                datetime.combine(transaccion.fecha_registro, datetime.min.time())
            )
        else:
            fecha_creacion = timezone.now()
        
        transaccion.fecha_creacion = fecha_creacion
        transaccion.fecha_actualizacion = fecha_creacion
        transaccion.save(update_fields=['fecha_creacion', 'fecha_actualizacion'])


def reverse_fill_timestamps(apps, schema_editor):
    """
    Operación reversa: establece los campos a None.
    """
    Transaccion = apps.get_model('api', 'Transaccion')
    Transaccion.objects.all().update(fecha_creacion=None, fecha_actualizacion=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_evidencia_options_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_timestamps, reverse_fill_timestamps),
    ]
