# Generated by Django 5.2.8 on 2025-11-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fill_transaction_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]

