# Generated by Django 5.2.8 on 2025-11-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_make_transaction_timestamps_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='archivo_path',
            field=models.CharField(blank=True, help_text='Ruta del archivo en Supabase Storage', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='archivo_url',
            field=models.URLField(blank=True, help_text='URL pública del archivo en Supabase Storage', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='archivo_evidencia',
            field=models.FileField(blank=True, help_text='Campo legacy - será eliminado después de migración', null=True, upload_to='evidencias/'),
        ),
    ]
