# Generated by Django 5.2.8 on 2025-11-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_supabase_storage_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion_evidencia',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='transaccion_evidencia',
            unique_together={('transaccion', 'evidencia')},
        ),
    ]
