# Generated by Django 5.2.8 on 2025-11-26 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_transaccion_evidencia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del invitado')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de invitación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación')),
                ('nombre_sugerido', models.CharField(blank=True, max_length=150, verbose_name='Nombre sugerido')),
                ('apellido_sugerido', models.CharField(blank=True, max_length=150, verbose_name='Apellido sugerido')),
                ('username_sugerido', models.CharField(blank=True, max_length=150, verbose_name='Username sugerido')),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Invitación de Usuario',
                'verbose_name_plural': 'Invitaciones de Usuarios',
                'ordering': ['-fecha_invitacion'],
                'indexes': [models.Index(fields=['token'], name='api_invitac_token_19e5e7_idx'), models.Index(fields=['email', 'estado'], name='api_invitac_email_aecee6_idx')],
            },
        ),
    ]
