# Generated by Django 5.2.8 on 2025-11-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_invitacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_transaccion',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto de la transacción (para mantener referencia)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proyecto'),
        ),
        migrations.AddField(
            model_name='log_transaccion',
            name='transaccion_id_eliminada',
            field=models.IntegerField(blank=True, help_text='ID de la transacción eliminada (para auditoría)', null=True),
        ),
        migrations.AddField(
            model_name='log_transaccion',
            name='transaccion_monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de la transacción eliminada', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='log_transaccion',
            name='transaccion_nro_documento',
            field=models.CharField(blank=True, help_text='Número de documento de la transacción eliminada', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subitem_presupuestario',
            name='categoria_subitem',
            field=models.CharField(blank=True, help_text='Categoría del subítem para validar contra la categoría del gasto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log_transaccion',
            name='transaccion',
            field=models.ForeignKey(blank=True, help_text='Transacción relacionada (null si fue eliminada)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaccion'),
        ),
    ]
