# Generated by Django 5.2.8 on 2025-12-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_categoria_subitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem_presupuestario',
            name='item_presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='api.item_presupuestario'),
        ),
    ]
