# Generated by Django 5.2.8 on 2025-12-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_subitem_presupuestario_item_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_principal',
            field=models.BooleanField(default=False, help_text='Indica si este usuario es el usuario principal de una organización. Los usuarios principales pueden crear organizaciones sin tener una asignada.'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_doc_transaccion',
            field=models.CharField(choices=[('factura electrónica', 'Factura Electrónica'), ('factura exenta', 'Factura Exenta'), ('boleta electronica', 'Boleta Electrónica'), ('boleta de honorarios', 'Boleta de Honorarios')], default='factura electrónica', max_length=50),
        ),
    ]
