# Generated by Django 5.2.8 on 2025-12-05 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_usuario_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_informe', models.CharField(help_text="Tipo de informe: 'estado', 'rendicion_oficial', etc.", max_length=50)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], help_text='Formato del archivo generado', max_length=10)),
                ('archivo', models.FileField(help_text='Archivo del informe generado', upload_to='informes/')),
                ('nombre_archivo', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se generó el informe')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del informe', null=True)),
                ('tamaño_archivo', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('generado_por', models.ForeignKey(blank=True, help_text='Usuario que generó el informe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_generados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que pertenece el informe', on_delete=django.db.models.deletion.CASCADE, related_name='informes_generados', to='api.proyecto')),
            ],
            options={
                'verbose_name': 'Informe Generado',
                'verbose_name_plural': 'Informes Generados',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['proyecto', 'fecha_generacion'], name='api_informe_proyect_1938e7_idx'), models.Index(fields=['tipo_informe', 'formato'], name='api_informe_tipo_in_e0d0ce_idx')],
            },
        ),
    ]
